.github/actions/getPreReleaseTag/action.yml
.github/workflows/githubRelease.yml
README.md

Prerelease-cca

---

.github/actions/gitConfig/action.yml
.github/workflows/automerge.yml
.github/workflows/ctcClose.yml
.github/workflows/ctcOpen.yml
.github/workflows/devScriptsUpdate.yml
.github/workflows/githubRelease.yml
.github/workflows/publishTypedoc.yml
.github/workflows/tarballs.yml
.github/workflows/validatePR.yml

What does this PR do?
Switches the account used for GHA CI.
What issues does this PR fix or reference?
@W-9073995@

chore: change env var

---

.github/actions/versionInfo/action.yml

Reference the `oclif.update.s3.folder` value from the `package.json`
[@W-12167909@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12167909)

Reference oclif s3 folder

---

.git2gus/config.json

[@W-11992747@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11992747)

Add git2gus config

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml

nuts and external nuts should use latest-rc

feat: nuts-on-latest-rc

---

.github/workflows/devScriptsUpdate.yml

retry on the pr creation in dev-scripts updates
solves (example) https://github.com/salesforcecli/plugin-auth/actions/runs/4649270525/jobs/8227497141#step:14:24

feat: more retries

---

.github/workflows/packUploadMac.yml

this fixes across sf 1,2 and sfdx
handle errors like https://github.com/salesforcecli/cli/actions/runs/4921691534/attempts/1

feat: mac retries

---

.github/actions/ctcOpen/action.yml
.github/workflows/ctcOpen.yml

Ensure we check the status code on the response, exit 1 if id is not set. 
Merge after https://github.com/forcedotcom/change-case-management/pull/130
[@W-13206830@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13206830)

ctcOpen validation

---

.github/workflows/npmPublish.yml

Reverts salesforcecli/github-workflows#50

Revert "perf: no sfdx install for npm publish"

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml

test: nuts without sfdx

---

.github/workflows/npmPublish.yml

Cleaning up the npm release script with some ternary-ishes
See [make-pr-for-release](https://github.com/salesforcecli/cli/blob/main/.github/workflows/make-pr-for-release.yml#L56-L65) for a working example
[@W-13799665@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13799665)

fix: npm release refactor

---

.github/workflows/stampyUpload.yml

callable workflow that downloads from AWS and uploads to stampy
validation: https://github.com/salesforcecli/cli/actions/runs/6085559663/job/16510089625

feat: upload to stampy

---

.github/actions/yarnInstallWithRetries/action.yml

[@W-14169311@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14169311)

chore: ignore scripts on yarn install

---

.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

> merge after 2023-10-24
as of 2023-10-24
latest = 21
lts = 20
so this keeps 18 going (EOL 2025-04-30)

ci: 18,20,21

---

.github/workflows/nut.yml

chore: skip manifest if not plugin

---

.github/workflows/nut.yml

Working here https://github.com/iowillhoit/gha-sandbox/actions/runs/6738385879/job/18317845763#step:4:3

chore: cross-os jq 'has'

---

.github/workflows/npmPublish.yml

This was a temp fix, reverting it.

Revert pinned prm version

---

.github/workflows/devScriptsUpdate.yml

Gha token name

---

.github/workflows/validatePR.yml

I want pr-validation to pass for something like https://github.com/forcedotcom/cli/issues/1234

feat: match cli issues repo links

---

.github/actions/determineNodeVersions/action.yml

Reverts salesforcecli/github-workflows#100
failed QA https://github.com/salesforcecli/plugin-org/actions/runs/9020688826/job/24786409574

Revert "Use node 'current' in UT, allow disable"

---

.github/workflows/tarballs.yml

[@W-12592230@](https://gus.lightning.force.com/a07EE00001LmkfkYAB)

feat: upload tarballs to github

---

.github/workflows/tarballs.yml

fixes https://github.com/salesforcecli/cli/actions/runs/9320566889/job/25657631753?pr=1701

fix: only upload to release if uploading tarballs

---

.github/workflows/ctcOpen.yml
.github/workflows/npmPublish.yml

chore: remove always() check in npm-publish

---

.github/workflows/validatePR.yml

fix: add reference to vscode issues

---

.github/workflows/validatePR.yml

- Read steps output from an env
- Adds `name`s to all steps
- Removes vague "github issue" match (`#[0-9]+`)
Part of [@W-16223935@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16223935)

Use envs on validate PR

---

.github/workflows/preventTypescriptDep.yml
.github/workflows/unitTest.yml
.github/workflows/unitTestsLinux.yml

@W-15981337@
see: 
https://github.com/forcedotcom/source-deploy-retrieve/pull/1373
first commit, without TS dep, passes https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/10045614955/job/27763259371
second commit, with TS dep, fails https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/10045668116/job/27763423256
note: will need to change `@wr/noTS` reference to `@main` before merging

feat: add new check to prevent TS direct dep

---

.github/workflows/npmPublish.yml

feat: no ctc for prerelease

---

.github/workflows/ctcClose.yml
.github/workflows/ctcOpen.yml
.github/workflows/npmPublish.yml

Update the CTC runners with a new ubuntu 24 runner
[Example of this working](https://github.com/salesforcecli/testPackageRelease/actions/runs/14340083942/job/40196942132#step:6:7)
[@W-18227847@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18227847)

W-18227847 Update ctc runners

---

.github/workflows/nut.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

[@W-18228933@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18228933)

W-18228933 temp disable wireit cache
