salesforcecli/github-workflows

.github/actions/getPreReleaseTag/action.yml
.github/workflows/githubRelease.yml
README.md

uses https://github.com/salesforcecli/conventional-changelog-action/tree/prereleases
the onRelease and onPushToMain workflows in your qa repo should look more like these: 
https://github.com/salesforcecli/testPackageRelease/blob/prerelease/demo/.github/workflows/onRelease.yml
https://github.com/salesforcecli/testPackageRelease/blob/prerelease/demo/.github/workflows/onPushToMain.yml
And, modify your package.json version to include the prerelease name and give it a starting number (x.x.x-beta.0) so that the workflows recognize it as a prerelease

Prereleases semver

---

.github/actions/windowsCachePerf/action.yml
.github/workflows/externalNut.yml
.github/workflows/lockFileCheck.yml
.github/workflows/nut.yml
.github/workflows/unitTest.yml

1. add faster windows cache algorithm per gha guidance https://github.com/actions/cache/blob/main/workarounds.md#improving-cache-restore-performance-on-windowsusing-cross-os-caching
2. testkit setup retries 2 for all nuts/extNuts
3. lockfile check as a separate workflow
4. caching for node_modules
5. 2 nuts retries
6. ut can optionally run on a single os so we can start linux nuts without waiting on windows ut

feat: caching, optimizations, retries

---

.github/workflows/unitTest.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

Calling the `unitTest.yml` file from a plugin (`test.yml`) with the conditional OSes made the GHA flow cluttered and confusing. I split the two OS unit tests into their own file and kept the base `unitTest` file for backward compatibility. 
**BEFORE**
**AFTER**

Split unit tests

---

.github/actions/renameMacPkg/action.yml
.github/workflows/packUploadMac.yml

> This needs to be merged at the same time as https://github.com/salesforcecli/sfdx-cli/pull/717
Adds a job to the workflow that packages and uploads Mac installers to copy & rename the intel Mac `.pkg` file produced by oclif from `<myCLI>-x64.pkg` to `<myCLI>.pkg` to avoid a breaking change for the `sfdx` CLI's download URLs.
@W-11963360@

feat: rename intel mac pkg

---

.github/workflows/ctcOpen.yml

`ctcOpen` [failed silently](https://github.com/salesforcecli/cli/actions/runs/3698754560/jobs/6265343850), which in turn caused `ctcClose` [to fail](https://github.com/salesforcecli/cli/actions/runs/3698754560/jobs/6265388047) because it didn't have a valid id. From what I can tell, none of these files changed recently. I believe this "passed" because the exit code was swallowed by the `echo`. 
Example:

Seperate command from echo

---

.github/workflows/ctcOpen.yml

We have had `ctcOpen` fail often. Most of the time it will work on a retry. This adds retries and will (hopefully) stop the build with exit code 1 if it fails.
Here is an example script that you can test with:
```sh
#! /bin/bash
ATTEMPT=1
MAX=5
DELAY=5 # seconds
function CREATE_CHANGE_CASE {
FOO=$(echo '{"foo": "bar"}' | jq -r '.baz')
if [[ "$FOO" == null ]]; then
return 1
fi
}
while true; do
CREATE_CHANGE_CASE && break || {
if [[ $ATTEMPT -lt $MAX ]]; then
((ATTEMPT++))
echo "Change Case creation failed - trying again ($ATTEMPT/$MAX)"
sleep $DELAY;
else
"Failed to create a Change Case after $ATTEMPT attempts"
exit 1
fi
}
done
echo "FOO IS: $FOO";
```

Retry ctcOpen and properly exit with 1 to stop build

---

.github/actions/ctcOpen/action.yml

[The "optional step" job](https://github.com/iowillhoit/gha-sandbox/blob/main/.github/workflows/needing-an-optional-job-alternate.yml) that I got working will not work when calling a workflow. 
`reusable workflows should be referenced at the top-level 'jobs.*.uses' key, not within steps`
I am going to try moving `ctcOpen` to an action so that I can call it in a step
I will use `runs-on: static-ip-ubuntu-runners` on the Job that will call this ^

Add ctcOpen action

---

.github/workflows/nut.yml

Allows you to configure NUT retries (defaults to 3). If you have certain NUTs that need to be ran more (or fewer) times, you can break them into different jobs. Example:
[@W-12594965@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-12594965)
```yml
[...]
nuts-fail-fast:
needs: linux-unit-tests
uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
secrets: inherit
strategy:
matrix:
os: [ubuntu-latest, windows-latest]
command:
- 'yarn test:nuts:convert'
- 'yarn test:nuts:commands:other'
fail-fast: false
with:
os: ${{ matrix.os }}
command: ${{ matrix.command }}
retries: 1  # <-------------------- note retries here
nuts-retry-a-lot:
needs: linux-unit-tests
uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
secrets: inherit
strategy:
matrix: …
```

Allow configuring nut retries

---

.github/workflows/tarballs.yml

I keep seeing S3 errors during this step, after retrying it eventually passes.
Example: https://github.com/salesforcecli/sfdx-cli/actions/runs/4502666115/jobs/7924813403?pr=1046#step:5:32

Retry pack:tarball

---

.github/workflows/externalNut.yml

run external nuts against a non-main branch.  
also speeds up git cloning by using --single-branch

feat: git single clone of chosen branch

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml

all nut secrets are params so they can be used across gh organization boundaries
[@W-12083615@](https://gus.lightning.force.com/a07EE00001DTeIGYA1)
proof it works on existing nuts (secrets:inherit)
https://github.com/salesforcecli/plugin-user/actions/runs/4601960461
proof it works with secrets passed in explicitly
https://github.com/forcedotcom/change-case-management/actions/runs/4600554348/jobs/8127337773

feat: parameterize nut secrets for reuse outside salesforce gh organization

---

.github/actions/yarnInstallWithRetries/action.yml
.github/workflows/externalNut.yml
.github/workflows/inclusionTest.yml
.github/workflows/npmPublish.yml
.github/workflows/nut.yml
.github/workflows/packUploadMac.yml
.github/workflows/packUploadWindows.yml
.github/workflows/publishTypedoc.yml
.github/workflows/tarballs.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

retries around yarn install since it sometimes timeout/503
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/4602154013/jobs/8130861374
git clone will sometimes 429
https://github.com/salesforcecli/plugin-source/actions/runs/4621491649/jobs/8173050988?pr=800

reat: retry yarn installs and git clone

---

.github/workflows/githubRelease.yml
.github/workflows/npmPublish.yml

allow secrets to be passed in for the release/publish actions.
for sharing actions across enterprise boundaries (ie, oclif)
usage as qa:
https://github.com/oclif/oclif/actions/runs/4855684156/jobs/8654486421#step:11:113

Secrets-input

---

.github/workflows/validatePR.yml

with CI, we have a decent amount of PRs that fix CI issues, not WI or gh issues.
ex: https://github.com/salesforcecli/plugin-packaging/pull/324
The presence of a gha run link should call PR validation to pass

feat: gha links makes valid PRs

---

.github/workflows/devScriptsUpdate.yml

I'd like to prevent devScripts update from running while the libraries are in transition for es2021.

chore: disable weekend dev-scripts updates

---

.github/workflows/packUploadMac.yml
.github/workflows/packUploadWindows.yml
.github/workflows/tarballs.yml

allows a CLI building tarballs/installers to set its nodeVersion.  defaults to lts when not set

chore: allow setting of node-version

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml

installs beta channel because 
`@^2` won't resolve `2.0.0-beta.47` causing this failure 
`error Couldn't find any versions for "@salesforce/cli" that matches "^2"`
https://github.com/salesforcecli/plugin-apex/actions/runs/5149961026/jobs/9273588342?pr=143

fix: install @salesforce/cli@beta

---

.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

run UT on node 20.
this requires newer versions of eslint-jsdoc, but that should be everywhere now because of dev scripts

feat: test on latest node (currently 20)

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml

> merge after sf v2 GA 
stops installing the `beta` for nuts/extNuts

feat: use sf v2 for nuts after GA

---

.github/workflows/npmPublish.yml

it *might* be possible to do this better (install plugin-trust and call it, or remove the --omit-dev to get all the deps from PRM, which should include plugin-trust, and then use `./bin/dev` to call that command) so we avoid installing the entire CLI
proof of work 
https://github.com/salesforcecli/testPackageRelease/actions/runs/5558708048/jobs/10154124756

chore: use sf, not sfdx for npm publish

---

.github/workflows/create-github-release.yml

Adds `oclif readme` to the `create-github-release` step. 
We use [TriPSs/conventional-changelog-action](https://github.com/TriPSs/conventional-changelog-action) to bump versions and build changelogs. We can run this without any changes/commits/pushes and just get next the "next version" in the output. We then can pass that to `oclif readme` with `OCLIF_NEXT_VERSION`. 
Then we run the conventional-changelog-action again to generate and commit everything (including the readme changes)
Notes:
- I remove the `v` in the [source links](https://github.com/oclif/oclif/blob/main/src/commands/readme.ts#L206) using `sed`. We could make a flag for `oclif readme` if we wanted to 🤷 
- We discussed adding a `"readme": "oclif readme"` script to the `package.json` and adding that to wireit's `build` but …

Add oclif readme command

---

.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

Drop `lts/-1` from unit tests since we won't be supporting node 16 going forward

feat: remove lts/-1 from test matrix

---

.github/workflows/create-github-release.yml

Use `yarn tsc` before `oclif readme` since oclif plugins don't have a `compile` script

chore: use yarn tsc

---

.github/workflows/unitTestsWindows.yml

windows UT timeout sometimes.
ex: https://github.com/salesforcecli/plugin-org/actions/runs/6289834751/attempts/1?pr=808
reruns tend to solve them.  So automate that.

ci: retry windows UT once

---

.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

The `wireit` cache can sometimes fail ([example](https://github.com/salesforcecli/plugin-dev/actions/runs/6372109495/job/17294641884#step:8:15)). This PR will continue on with unit tests if the wireit cache setup fails. Also adds retries for linux tests.
Wireit Issue to handle this better: https://github.com/google/wireit/issues/641
Wireit PR where they added some connection retry logic: https://github.com/google/wireit/pull/510/files
[@W-14221405@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14221405)

Continue if wireit cache fails

---

.github/workflows/externalNut.yml

Adds `ignoreScript` option to `externalNut` to pass in `--ignore-scripts` to the yarn install that is run inside of node_modules. See it working here: https://github.com/oclif/core/actions/runs/6395984185/job/17360979081

feat: add ignoreScript options to externalNut

---

.github/actions/ctcOpen/action.yml
.github/actions/determineNodeVersions/action.yml
.github/actions/retry/action.yml
.github/actions/yarnInstallWithRetries/action.yml
.github/workflows/ctcOpen.yml
.github/workflows/devScriptsUpdate.yml
.github/workflows/externalNut.yml
.github/workflows/nut.yml
.github/workflows/packUploadMac.yml
.github/workflows/tarballs.yml
.github/workflows/unitTest.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

> **IMPORTANT**
> Don't merge before we replace `@ew/retry-wrapper` with `@main`
- Adds a wrapper for `nick-fields/retry` with sensible defaults
- Adds an action for calculating Node Version and Node LTS -1 for unit tests
- Works with `NODE_VERSION_OVERRIDE` [[example](https://github.com/salesforcecli/testPackageRelease/actions/runs/6734126949) with `18.15.0` and `16`]
- Works without `NODE_VERSION_OVERRIDE` [[example](https://github.com/salesforcecli/testPackageRelease/actions/runs/6723446808/job/18273548456) with `lts/*` and `lts/-1`]
- Finds the previous LTS by looking for the previous even number. [[example](https://github.com/salesforcecli/testPackageRelease/actions/runs/6734178025) with `17` and `16`]
[@W-14338799@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W …

Retry wrapper and determine node versions

---

.github/workflows/npmPublish.yml

[flood-io/is-published-on-npm](https://github.com/flood-io/is-published-on-npm) is stale and uses the "[soon to be deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)" `set-output` format for setting values. 
This PR replaces it with a simple bash script before it breaks. 
Here is a similar shell script you can use for QA. 
- `cd` into a plugin dir (e.g. `plugin-info`)
- `touch npm-test.sh`
- Add the following
```sh
VERSION="2.1.11"
RESPONSE=$(npm view .@$VERSION version --json --silent)
if [ "$RESPONSE" = "\"$VERSION\"" ]; then
echo "published=true"
else
echo "published=false"
fi
```
- `source npm-test.sh`
- Change `VERSION` to a published and non-published version …

Replace flood-io/is-published-on-npm

---

.github/workflows/npmPublish.yml

Prevents the npm version check from exiting with a 1 (and ending the job)
[@W-14488765@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14488765)

Prevent exit code 1

---

.github/workflows/create-github-release.yml
.github/workflows/githubRelease.yml

The GHA `actions/create-release@v1` has been deprecated for a while. The PR replaces that action with a similar action
[@W-14488760@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14488760)
- PR: https://github.com/salesforcecli/testPackageRelease/pull/33
- Create prerelease action: https://github.com/salesforcecli/testPackageRelease/actions/runs/7022349666/job/19106430823#step:8:3
- Prerelease Release: https://github.com/salesforcecli/testPackageRelease/releases/tag/3.2.1-dev.0
- Prerelease Publish Action: https://github.com/salesforcecli/testPackageRelease/actions/runs/7022366002
- NPM version: https://www.npmjs.com/package/@salesforce/test-plugin117/v/3.2.1-dev.0
> PR was merged...
- Create release action: …

Replace actions/create-release@v1

---

.github/workflows/externalNut.yml
.github/workflows/nut.yml
.github/workflows/unitTestsWindows.yml

fix errors like https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/7587086107/job/20666713904#step:2:50
https://github.com/forcedotcom/source-deploy-retrieve/pull/1218 shows this in action.  Had to keep it from running on linux using `if` to prevent `error: could not lock config file /etc/gitconfig: Permission denied`

fix: windows longpath

---

.github/actions/getGithubUserInfo/action.yml
.github/actions/gitConfig/action.yml
.github/workflows/create-github-release.yml
.github/workflows/devScriptsUpdate.yml
.github/workflows/githubRelease.yml
.github/workflows/publishTypedoc.yml
README.md

> [!WARNING]
> Do not merge yet, additional PRs incoming
> TODO: Revert `ew/external-friendly` branch refs
We hard coded our svc-cli-bot username/email in a few spots. Making these workflows not useable to external developers. 
This PR looks up the username/password based on the Github Token being used. Additional changes are made to take advantage of this lookup.
Example of a Release working on an external plugin: https://github.com/iowillhoit/plugin-workflow-test/actions/runs/7748104245
Example of this working on an internal plugin (using secrets inherit) https://github.com/salesforcecli/testPackageRelease/actions/runs/7759564485/job/21163873201#step:8:27
[@W-14809762@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14809762)
Other PRs: …

External developer friendly changes

---

.github/actions/generateOclifReadme/action.yml
.github/workflows/create-github-release.yml

Add ability to pass in custom command for readme generation
🟢 Passing build: https://github.com/oclif/oclif/actions/runs/8362307426/job/22892575033
🟢 Generated readme with custom command: https://github.com/oclif/oclif/tree/4.6.1-dev.0/docs

feat: add readme-command input

---

.github/actions/generateOclifReadme/action.yml

Github Actions handle inputs differently than Workflows. Everything is a string. So `'false'` was truthy and causing the `--mutli` flag to be added. 
Related to [@W-15295078@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15295078)

Input is a string in Actions

---

.github/workflows/externalCompile.yml

kinda like external NUT, but less specific.
1 `yarn compile` or `yarn build` (see if this library change will break consumers)
2 `yarn test` (see if this library change will break consumers' UT)
QA: see it in action here https://github.com/forcedotcom/ts-types/pull/296
> after merging this, change the branch name on https://github.com/forcedotcom/ts-types/pull/296

feat: external [compile/lint/UT]

---

.github/actions/determineNodeVersions/action.yml

We had disabled Node `current` in unit tests when we were having issues with Node 21. This brings it back along with the ability to disable it with an env var in Github Actions (either at the org or repo level). 
[@W-15716084@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15716084)

Use node 'current' in UT, allow disable

---

.github/workflows/tarballs.yml

supply gh token for gh uploads
use aws in env only where needed

fix: secrets for gh upload, aws secrets only where needed

---

.github/workflows/packUploadMac.yml
.github/workflows/packUploadWindows.yml
.github/workflows/tarballs.yml

WI: it doesn't save time to download the tarballs to reuse vs. packing them from source in parallel.  Saving 20s would take extra work to oclif pack cmd, not positive ROI.
@W-12592230@

ci: upload mac/win installers to release

---

.github/workflows/ctcOpen.yml

Github Actions sets -e on the shell by default making it exit immediately on an error. 
`shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}`
This prevented us from getting useful error information from an oclif command in GHA. Temporarily setting `+e` allows us to get the error json to parse later. 
Example of this working: https://github.com/iowillhoit/gha-sandbox/actions/runs/9406451924/job/25909919754

Collect info on error

---

.github/actions/generateOclifReadme/action.yml
.github/actions/get-json-property/action.yml
.github/actions/getGithubUserInfo/action.yml
.github/actions/getPreReleaseTag/action.yml
.github/actions/parse-semver/action.yml
.github/actions/retry/action.yml
.github/workflows/create-github-release.yml
.github/workflows/devScriptsUpdate.yml
.github/workflows/externalNut.yml
.github/workflows/githubRelease.yml
.github/workflows/nut.yml
.github/workflows/packUploadWindows.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml
.github/workflows/validatePR.yml
README.md

* `actions/checkout`  https://github.com/actions/checkout
* Was v3
* **Use v4**
* `actions/setup-node` https://github.com/actions/setup-node
* Was v3
* **Use V4**
* `actions/github-script` https://github.com/actions/github-script
* Was v3
* **Use V7**
* I don’t thing there are any breaking changes since we only use this for `core.setFailed`
* `actions/cache` https://github.com/actions/cache
* Was v3
* **Use v4**
* `TriPSs/conventional-changelog-action`  https://github.com/TriPSs/conventional-changelog-action/
* 🟢 Review completed
* Was `9962c3267b32873dbc552a38a8397194361e1101`
* Use `3a392e9aa44a72686b0fc13259a90d287dd0877c`
* `notiz-dev/github-action-json-property` https://github.com/notiz-dev/github-action-json-property
* 🟢 Replaced
* Was `7a701887f4b568b23eb7b78bb0fc49aaeb1b68d3`
* …

Update external actions

---

.github/workflows/npmPublish.yml

While attempting to test the `failureNotifications` workflow, I discovered that if an npm version is already published, the workflow just skips the rest of the steps and we don't get a failure notification https://github.com/salesforcecli/testPackageRelease/actions/runs/9471234489
Note this was skipped: https://github.com/salesforcecli/testPackageRelease/actions/runs/9471239334
This will now exit the workflow and should cause the `failureNotification` workflow to run.
Part of [@W-15960060@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15960060)

Exit if already published to npm

---

.github/actions/get-json-property/action.yml
.github/workflows/devScriptsUpdate.yml

Part of [@W-15960060@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-15960060)
Proof of this working here: https://github.com/iowillhoit/gha-sandbox/actions/runs/9473211921/job/26100309440

Dev scripts json reference

---

.github/workflows/validatePR.yml

This regex should work for all github org/repo combos (based on [this SO](https://stackoverflow.com/questions/59081778/rules-for-special-characters-in-github-repository-name#comment132563138_59082561))
Example of this working for the vast majority of our repos: https://regex101.com/r/7UUkbm/1
[@W-16027880@](https://gus.lightning.force.com/a07EE00001ugi05YAA)

fix: org/repo regex

---

.github/workflows/unitTestsLinux.yml

allows to skip the ts-dep-check.
input var, default to `false` and not required so not breaking change.
Tested here (eslint plugin does ship TS, fine b/c it's a devDep): 
https://github.com/salesforcecli/eslint-plugin-sf-plugin/pull/447
https://github.com/salesforcecli/eslint-plugin-sf-plugin/pull/447/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R14
https://github.com/salesforcecli/eslint-plugin-sf-plugin/actions/runs/10097522355/job/27922579850

fix: allow to skip ts-dep check

---

.github/workflows/unitTestsLinux.yml

follow up of https://github.com/salesforcecli/github-workflows/pull/120
it was checking boolean values against strings, so all workflows got the ts-dep-check disabled unless the input var with any value was provided.
found here (see ts-dep check didn't run, the workflow didn't specify the input var: 
https://github.com/salesforcecli/plugin-data/pull/1002/commits/932146d1ff9337c2f16c9c46b10cb863e8a5b75e
tested with `input.skipTsDepCheck` false/true here (see bool=true/false commits) here:
https://github.com/salesforcecli/eslint-plugin-sf-plugin/pull/447
and with no input var (should do the check) here:
https://github.com/salesforcecli/plugin-data/pull/1002

fix(skipTsDepCheck): check boolean, not string

---

.github/workflows/preventTypescriptDep.yml

Run `yarn why typescript` if typescript was found in production node_modules

chore: yarn why typescript

---

.github/workflows/npmPublish.yml

I think this is causing npm publish on prereleases to skip
Reverts salesforcecli/github-workflows#122

Revert "feat: no ctc for prerelease"

---

.github/actions/determineNodeVersions/action.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

Allows you to disable the node version-1 in unit tests
You would enable this feature by setting `UT_DISABLE_NODE_PREVIOUS` in your Github org's (or repo's) Action Variables ([docs for org](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#creating-configuration-variables-for-an-organization))
[@W-16617566@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16617566)
Here is a script for QA. Run `source theFile.sh`
```shell
#!/bin/sh
test() {
NODE_VERSION_CURRENT="current"
if [ "$INPUTS_NODE_DISABLE_CURRENT" = "true" ] || [ -n "$INPUTS_NODE_VERSION_OVERRIDE" ]; then
NODE_VERSION_CURRENT=""
fi
NODE_VERSION="lts/*"
if [ -n "$INPUTS_NODE_VERSION_OVERRIDE" ]; then
NODE_VERSION="$INPUTS_NODE_VERSION_OVERRIDE" …
```

Allow skipping node version-1 in unit tests

---

.github/workflows/stampyUpload.yml

Upload the new arm64 to stampy for signing. 
NOTE: This likely needs to wait until https://github.com/oclif/oclif/pull/1559 is merged. I have a feeling the `cp` steps would cause this to fail if the `exe` didn't exist. 
[@W-16853993@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-16853993)

Upload arm64 to stampy

---

.github/workflows/preventTypescriptDep.yml

Run `npm ls typescript` when typescript is found because it often has additional information that `yarn why` doesn't provide

chore: update error output

---

.github/workflows/validatePR.yml

Validates work item in the PR title and body.
[@W-17694802@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17694802)

W-17694802 Validate WI in PR title

---

.github/workflows/tarballs.yml

GitHub is deprecating Ubuntu 20 runners.  The only CLI repo that uses Ubuntu 20 is this one so bumping to a new Ubuntu 22 runner.
@W-17811792@

W-17811792 - fix: use ubuntu 22 8 core large runner

---

.github/workflows/ctcOpen.yml
.github/workflows/npmPublish.yml

Merge this first: https://github.com/forcedotcom/change-case-management/pull/158
Part of the pipeline compliance work. We need to link from the Change Case to where the test were ran.
I chose to link back to the Github Release because it is possible for a Release to contain more than one PR merge. Thanks to our change logs, the links to the PRs are listed in the Github Release body
[@W-17239852@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17239852)
Also part of [@W-18023620@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18023620)

W-17239852 Add --test-environment to change case

---

.github/workflows/nut.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

We were affected by this brownout period due to caching methods changing
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
Google fixed this [here](https://github.com/google/wireit/issues/1297#issuecomment-2794737569) 
[@W-18228933@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18228933)

W-18228933 use new wireit cache

---

.github/workflows/nut.yml
.github/workflows/unitTestsLinux.yml
.github/workflows/unitTestsWindows.yml

Updates the wireit action to v2
Provides a temp-workaround to ensure that repos have a new-enough local `wireit`.
Proof of this working: https://github.com/salesforcecli/plugin-org/actions/runs/14577349675/job/40886308636
FYI: this was bumped in [dev-scripts here](https://github.com/forcedotcom/dev-scripts/pull/387) 
See [this thread](https://github.com/google/wireit/issues/1297#issuecomment-2794737569) for more details. 
[@W-18302796@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18302796)

W-18302796: update to wire action v2

---

.github/actions/ctcOpen/action.yml
.github/workflows/ctcOpen.yml

Passes in a new flag for you to be able to set the Service__c on a Case
[Proof of this working](https://gus.lightning.force.com/lightning/r/Case/500EE00001XuOp3YAF/view) (search for service)
**Merge after https://github.com/forcedotcom/change-case-management/pull/159**
The test-env is the same changes as https://github.com/salesforcecli/github-workflows/pull/135. I need to add it to the Action because the CLI promotion uses that one.
[@W-18709286@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18709286)

W-18709286 adds service and test-env

---

.cursor/rules/yaml-checklist.mdc
.github/actions/npmInstallWithRetries/action.yml
.github/actions/yarnInstallWithRetries/action.yml
.github/workflows/externalNut.yml
.github/workflows/npmPublish.yml
README.md

some repos that use npm (jsforce, most of vscode ext) use npm, not yarn.
but they'd like to use the shared publish stuff.

feat: allow npm for publish and install

---

.github/workflows/npmPublish.yml

Adds a temporary check for vulnerable npm packages from a recent supply chain attack
https://www.sonatype.com/blog/npm-chalk-and-debug-packages-hit-in-software-supply-chain-attack
[@W-19595600@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-19595600)
Spoofed examples of this working

W-19595600: check for vuln packages
